### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [gristlabs/grist-help#183]
Hello!

I found this project from https://hackaday.com/2022/09/23/a-spreadsheet-for-the-python-hacker/

Could you please add information about the license of this repository — is it allowed to copy, change and use the content in any purpose?

I see https://github.com/gristlabs/grist-core uses Apache-2.0 license.

It would be great to see any popular open source license here also.

**Comment by vazhnov** [comment]
Creative Commons Attribution-ShareAlike 4.0 International — awesome!
@paulfitz, thank you!

**Comment by paulfitz** [comment]
@vazhnov you're welcome, thanks for the nudge.
