### ISSUE TITLE
Translating Documentation in French

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-help#213]
Hey there 👋🏼 

We are working on translating the Grist documentation to french, and were wondering what the best way to go about it was ?

Should we fork this repo and create a `help_fr/` folder for now with all the translated Markdown content of `help/` in it ? Any tool you would like us to use ?

Cheers !

cc @dsagal @paulfitz @anaisconce

**Comment by paulfitz** [comment]
Hi @vviers, that is exciting!

Yes, forking and a `help_fr/` folder seems the most practical. No-one on our team is familiar with tooling in maintenance of translations of technical documentation. I poked around and found gitlocalize usable, but have no particular reason to recommend it. We now use weblate for translation of the app, but it doesn't have particular support for documents. I see people doing po4a-based workflows with it, but it looks complicated. Some on your team used crowdin for translation of the app, and crowdin does apparently have some support for document translation. In short, no ideas here, we're ready to follow your lead on this.

**Comment by vviers** [comment]
Following up on this as we're preparing to really put some time and effort into this. Is forking + a `help_fr/` folder still the best option at this stage ?

Would you like us to investigate what the best tool would be to handle multi-language documentation ?

**Comment by fflorent** [comment]
I am closing this issue, I think we can consider this work done now. In case I am wrong doing so, please don't hesitate to reopen it.
