### ISSUE TITLE
[GitLocalize] Please invite me to the translation team

### ISSUE THREAD

**Issue by ricpol** [gristlabs/grist-help#404]
### GitLocalize account creation

- [X] My account is created, you can invite me

### Languages you would like to help translate

Others (please detail below)

### Other languages (optional)

Italian

**Comment by fflorent** [comment]
Hello @ricpol!

I opened PR #405 to add the Italian language in the help support, I wait for a review and a merge from Grist Labs. I would then be able to add the Italian language in GitLocalize and you may then start translating.

BTW, I used some Python script I made quickly to ask GPT to translate every page. Would you like me to take time to cleanup this script, document it and make it available? 
It would require an Open AI api key. FWIW, it cost me 10$ to credit my api key and I consumed about 4$ to translate everything.

**Comment by ricpol** [comment]
ok thanks I'll be super-busy with my day job for a month or so anyway, so I'll just wait... 
I think I'll translate by hand anyway... I have already translated all the Grist GUI, and I also maintain an [ongoing Italian translation](https://github.com/ricpol/pytutorial-it) of the official python tutorial, so... I'll be fine I think!

**Comment by vviers** [comment]
Bravissimo !
