### ISSUE TITLE
[GitLocalize] Please invite me to the translation team

### ISSUE THREAD

**Issue by bipenett** [gristlabs/grist-help#419]
### GitLocalize account creation

- [X] My account is created, you can invite me

### Languages you would like to help translate

Others (please detail below)

### Other languages (optional)

Portuguese

**Comment by fflorent** [comment]
Sorry for the delay, this should be done!

If you would like to take advantage of machine translation, please give feedback on this issue: #400 

Thank you for volunteering to translate!
