### ISSUE TITLE
Language switcher has odd styling in Safari 17.6

### ISSUE THREAD

**Issue by nbush** [gristlabs/grist-help#443]
![image](https://github.com/user-attachments/assets/8f35386e-b436-4f6d-9892-1c54b81349ab)

See image. Looks fine in Firefox. @fflorent any ideas?

**Comment by fflorent** [comment]
@nbush I am not very surprised, unfortunately, styling dropdown lists (built using the `<select>` HTML elements) is limited.

There seems to exist a `-webkit-appearance: none;` that we can add to override the browser styling.

**Comment by fflorent** [comment]
I have proposed a fix. Is the problem still present in this preview?
https://deploy-preview-452--grist-help-preview.netlify.app/

I have not fixed the styling of the options yet. I feel like it is a smaller problem that we may fix when the support website will be rewamped.

**Comment by dsagal** [comment]
I confirm this fixes the weird background on Safari, but it loses the arrow that indicates that it is a dropdown. Unfortunately, the arrow is also gone on Firefox and Chrome.

**Comment by fflorent** [comment]
@manuhabitela is helping me on this one
